[package]
name = "host-fn-benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
wat = "1.240"
wasmi = "1.0.9"
wasmtime = "43.0.0"
wasmer = { version = "7.1.0", default-features = false, features = ["compiler", "llvm", "sys", "wat"] }
wasmer-compiler-llvm = "7.1.0"
wasmedge-sdk = { version = "0.14.0", features = ["standalone"] }

[profile.release]
debug = true
